#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17 ../../../Sources/RAINBOWCOLORS.cpp ../../../Sources/SYSFILEACCESS.cpp ../../../Sources/GPIO.cpp  ../../../Sources/PWM.cpp ../../../Sources/TB6612FNG.cpp TB6612FNG_1.1.cpp -lpthread -o TB6612FNG_1.1.out
echo "Finished"
