#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17 ../../Sources/RAINBOWCOLORS.cpp ../../Sources/SYSFILEACCESS.cpp ../../Sources/GPIO.cpp  ../../Sources/PWM.cpp ../../Sources/TB6612FNG.cpp Listing_7.3.cpp -lpthread -o Listing_7.3.out
echo "Finished"
