#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17  ../../Sources/RAINBOWCOLORS.cpp ../../Sources/GPIO.cpp ../../Sources/BUTTON.cpp ../../Sources/LED.cpp Listing_3.4.cpp -lpthread -o Listing_3.4.out
echo "Finished"
