#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17 ../../../Sources/RAINBOWCOLORS.cpp ../../../Sources/SYSFILEACCESS.cpp ../../../Sources/MISCELLANEOUS.cpp  ../../../Sources/GPIO.cpp ../../../Sources/LED.cpp ../../../Sources/ADC.cpp  ../../../Sources/KEYPAD_5BUTTONS.cpp KEYPAD_5BUTTONS_1.2.cpp -lpthread -o KEYPAD_5BUTTONS_1.2.out
echo "Finished"
