#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17  ../../Sources/RAINBOWCOLORS.cpp ../../Sources/SYSFILEACCESS.cpp ../../Sources/MISCELLANEOUS.cpp ../../Sources/GPIO.cpp Listing_1.5.cpp -lpthread -o Listing_1.5.out
echo "Finished"