#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17 ../../Sources/RAINBOWCOLORS.cpp ../../Sources/SYSFILEACCESS.cpp ../../Sources/ADC.cpp Listing_5.2.cpp -lpthread -o Listing_5.2.out
echo "Finished"
