#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17 ../../Sources/RAINBOWCOLORS.cpp ../../Sources/SYSFILEACCESS.cpp ../../Sources/PWM.cpp Listing_4.3.cpp -lpthread -o Listing_4.3.out
echo "Finished"
