#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17 ../../../Sources/RAINBOWCOLORS.cpp ../../../Sources/SYSFILEACCESS.cpp ../../../Sources/MISCELLANEOUS.cpp  ../../../Sources/ADC.cpp  ../../../Sources/KEYPAD_5BUTTONS.cpp KEYPAD_5BUTTONS_1.1.cpp -lpthread -o KEYPAD_5BUTTONS_1.1.out
echo "Finished"
