#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17  ../../Sources/RAINBOWCOLORS.cpp ../../Sources/GPIO.cpp ../../Sources/BUTTON.cpp Listing_3.2.cpp -lpthread -o Listing_3.2.out
echo "Finished"
