#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17 ../../Sources/SYSFILEACCESS.cpp ../../Sources/MISCELLANEOUS.cpp ../../Sources/GPIO.cpp Listing_1.3.cpp -lpthread -o Listing_1.3.out
echo "Finished"
