#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17 ../../../Sources/RAINBOWCOLORS.cpp ../../../Sources/SYSFILEACCESS.cpp ../../../Sources/MISCELLANEOUS.cpp  ../../../Sources/PWM.cpp ../../../Sources/ADC.cpp ../../../Sources/SERVO.cpp ../../../Sources/CONTINUOUS_SERVO.cpp SM-S4303R_1.1.cpp -lpthread -o SM-S4303R_1.1.out
echo "Finished"
