#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17 ../../../Sources/RAINBOWCOLORS.cpp ../../../Sources/SYSFILEACCESS.cpp ../../../Sources/MISCELLANEOUS.cpp  ../../../Sources/PWM.cpp ../../../Sources/SERVO.cpp ../../../Sources/POSITION_SERVO.cpp SG90_1.1.cpp -lpthread -o SG90_1.1.out
echo "Finished"
