#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17 ../../Sources/SYSFILEACCESS.cpp ../../Sources/MISCELLANEOUS.cpp ../../Sources/PWM.cpp \
 Listing_4.1.cpp -lpthread -o Listing_4.1.out
echo "Finished"
