#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17 ../../../Sources/RAINBOWCOLORS.cpp ../../../Sources/SYSFILEACCESS.cpp ../../../Sources/GPIO.cpp  ../../../Sources/PWM.cpp ../../../Sources/TB6612FNG.cpp Listing_1.cpp -lpthread -o Listing_1.out
echo "Finished"
