#!/bin/bash

echo "Building BeagleBone Application..."
g++ -std=c++17  ../../Sources/RAINBOWCOLORS.cpp ../../Sources/SYSFILEACCESS.cpp \
		../../Sources/MISCELLANEOUS.cpp ../../Sources/GPIO.cpp Listing_1.1.cpp \
		-lpthread -o Listing_1.1.out
echo "Finished"
